work_dir: ./work_dir/ntu60/xview/ctrgcn_joint

# feeder
feeder: SourceCode.feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU_CV.h5
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  bone: False
  cat: True

test_feeder_args:
  data_path: data/ntu/NTU_CV.h5
  split: test
  debug: False
  window_size: 64
  p_interval: [0.95]
  bone: False
  cat: False


val_feeder_args:
  data_path: data/ntu/NTU_CV.h5
  split: val
  debug: False
  window_size: 64
  p_interval: [0.95]
  bone: False
  cat: False

# model
model: SourceCode.model.ctrgcn.Model
model_args:
  num_class: 60
  num_person: 2
  in_channels: 3
  graph: SourceCode.graph.ntu_rgb_d.Graph
  graph_args:
    part_aware_graph: 'full_graph'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 90
nesterov: True
